# Generated by Django 5.2.5 on 2025-09-12 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shippingaddress'),
    ]

    operations = [
    ]
